# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "CentOS-7-x86_64-Vagrant-1601_01"
  config.vm.box_url = "http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1601_01.VirtualBox.box"
  config.vm.boot_timeout = 600
  config.vm.synced_folder ".", "/vagrant" #, type: "nfs"

  config.vm.hostname = "one.vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--name", "one.vagrant", "--memory", "1024", "--cpus", "2"]
  end
  config.vm.network "private_network", ip: "192.168.35.80"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.verbose = "vv"
    ansible.limit = 'all'
  end
end
